# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_max_watts_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='power_curve_duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riderNo', models.CharField(max_length=30)),
                ('Max_watts_10seconds', models.IntegerField()),
                ('Max_watts_30seconds', models.IntegerField()),
                ('Max_watts_1min', models.IntegerField()),
                ('Max_watts_5min', models.IntegerField()),
                ('Max_watts_20min', models.IntegerField()),
                ('Max_watts_60min', models.IntegerField()),
            ],
        ),
    ]
